-- Migrate data from SQL Server to PostgreSQL using pgloader
pgloader \
    -- Connection parameters for source database
    -- ...
    -- Connection parameters for target database
    -- ...
    -- Select tables to migrate
    -- ...
