CREATE TABLE Employees (
  EmployeeID INT NOT NULL,
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  Email VARCHAR(100) NOT NULL,
  Salary MONEY NOT NULL,
  PRIMARY KEY (EmployeeID)
);
